### ISSUE TITLE
Game1: Lives problem

### ISSUE THREAD

**Issue by Magalii** [OpenWeek/app-for-a-KAP#21]
There is sometimes a problem with the live count.
- Sometimes a non-sti enemy touches Mireille and she doesn't lose a life. It seems to happen when she has just lost a life, so maybe there is a too long 'immunity time' before she can lose a life again.
- Sometimes she instantly dies while she still has lives left and isn't touched by anything. It seems to happen when she has been touched by a non-sti and lost a life, then the same non-sit arrives again. I have only seen this happen in that case, but it doesn't happen 100% of the time when this scenario occurs.

**Comment by FrancoisDuchene** [comment]
I think i may have fixed this problem, could you please check if the problem still up ?

**Comment by Magalii** [comment]
I have tested the game many times for both problems and they both seem fixed.
The only 'abnormality' there is now is that when a non-ist disease has touched the player (thus removing a life), it is always that same ennemy that comes up next.

**Comment by FrancoisDuchene** [comment]
That will need to be also fixed. If anyone still has bugs about this feature even after the fix, please post a message here

**Comment by FrancoisDuchene** [comment]
The abnormality should be fixed by now, could you verify this ?
