### ISSUE TITLE
Game1: Improving the learning part

### ISSUE THREAD

**Issue by Magalii** [OpenWeek/app-for-a-KAP#22]
- To make it better for people to learn what is an STI or not, I think it could be good to have an indication that you have missed an STI. Otherwise people can just avoid everything they are not sure are an STI or not and not learn that something is actually an STI. One could argue that it would make the game too simple, I don't really know what would be best. :)
- About the name of Mr Sida, I think it should be Mr VIH instead to make it clear that VIH is the actual transmissible virus and that 'sida' is a stage of the disease.

**Comment by FrancoisDuchene** [comment]
Another idea on this topic would be to have more fake ists that looks alike real sickness which arent STI, it's a bit obvious that some of them are fake :)

**Comment by FrancoisDuchene** [comment]
I added the two first propositions to the game. 
* Mister Sida has been changed to mister VIH
* After the game ended, the sicknesses that havent been catched are shown to the player. This is pretty rudimentary for now. 
   - First, sicknesses that arent catched are added to the endlist, even if later in the game, they are catched by the player. So if a player miss VIH once, then catch it anytime it appear later in the game, VIH will still be shown to it at the end. This is a question, do we keep this behavior, or do we do something else ?
   - Second, only the sickness name is displayed for now. I want to add the draw associated to the sickness but i think that a description could also be good, so it could be a bit informative to the player. Do you all think this is a good idea, or should i keep myself to this system ?
