### ISSUE TITLE
Game1: Improving the gameplay

### ISSUE THREAD

**Issue by Magalii** [OpenWeek/app-for-a-KAP#23]
Playing the game, I found two things to improve:
- Making sure that there is not too many non-sti or sti in a row
- Making sure that there is not too many enemies in the same lane in a row

**Comment by FrancoisDuchene** [comment]
After played the game a bit, i thought of different other ways to improve the gameplay :
  - When the player pause the game (for example come back to the Home screen of the phone), then come back, the game resume instantly. It would be great if the game paused himself on a pause screen with a "*resume*" button which would resume the game after certain time, let's say 3 secondes. 
  - In the same order of idea than the first proposition, adding a pause screen would be great
  - When the player misses an IST, a small "*Missed*" text appears to visually shows that the player missed one. This proposition also goes in the way of what was discussed in issue #22 
  - About the type of virus falling, the probably to get a different virus is equals for every different viruses saved. However, it is not related to "ist" and "fake-ist", it is related to the textures. So for instance, there are more textures of ist than fake-ist stocked on the disk. So there will be more probability to get an ist. For these two cases, this is not problematic (well that's subject to debating), however for the *bosses*, this may be. My proposition would be to have a certain number of viruses falling, then the player would have a boss. What the behavior of the boss should be is matter of debating, but i think it would greatly improve the gameplay to have a slighly different gameplay for this special kind of virus. Maybe do multiple different levels for the game ? Each one having a certain boss to beat ?
- A level of difficulty to adjust would also be great, like *easy*, *medium*, *hard*. Maybe we should make modify the acceleration value according to the difficulty ? Or the probability of having fake ists ? (as they are the bad guys there)

**Comment by FrancoisDuchene** [comment]
TODO list
- [X] Slow-start with pause when player pause quit the game and resume it
- [X] Pause button
- [ ] Missed text appearing when player misses an IST
- [ ] Make different game modes, *easy*, *medium* and *hard* (for more info check discussion below)

**Comment by FrancoisDuchene** [comment]
For the different levels of difficulty, i have yet another proposition. I'm abandoning the idea of having bosses (maybe in the future but not for alpha-1.0) to have only a certain amount of viruses to catch. The amount needed to pass to the next level is predefined by the difficulty. E.g. to get the *medium* difficulty, you have to catch at least 15 IST's. I can also play on the number of lifes remaining (e.g. you have only one life in hard mode), the score (e.g. you have to get 300 points at least) and the number of real ists you missed.
When we have a basic easy/medium/hard difficulties, we can even add more difficulty levels but it's not the priority right now.

My proposition is the following : 
Game | Difficulty level | Access conditions | Parameters
--------|------------------|------------------------|---------------
Game 1 | Easy | no requirement | 5 ists to catch, 3 lifes
 a | Medium | Succeed easy mode | 15 ists to catch, 3 lifes, have a score of at least 200 points
a | Hard | Succeed medium mode | 20 ists to catch, 1 life, have a score of at least 300 points
Game 2 | Succeed medium mode | a

**Comment by FrancoisDuchene** [comment]
The difficulty has been raised as stated in the earlier posts. I also added the possibility to lock levels. For instance, if a new user try to play the first game, only the easy mode will be unlocked. If he beat the easy mode, he will unlock the medium mode, and so on.

**Comment by FrancoisDuchene** [comment]
Another idea to make the player win points, is to take in count the speed and acceleration. More the speed is high, higher the points the player will earn by catching an IST.
