### ISSUE TITLE
General: Text Alignement w/ Labels and TextButtons

### ISSUE THREAD

**Issue by FrancoisDuchene** [OpenWeek/app-for-a-KAP#34]
Until now, this is quite an annoying process to correctly align a text with another object.
For example in Game 1, the alignment between an enemy texture and it's name. Only patience and hardcoding values for the text bounds (*x, y, width, height*) works until now. It makes it hell to correctly place the text or even use a ImageTextButton. Indeed without using borders, the image is scaled to exactly fits the text space. To add **padding** between the text and the texture, the dev has to play with the values of width and height of the button, thus making it nightmare each time the text length needs to be changed, as there's no convenient way to know the space in pixel needed taken by the text.

Therefore, a few methods should be added to handle this problem better :
- Write two methods to get the length and width of a text following a certain font (and there are many, therefore it needs to be generic).
- A method to know the position in x and y of the label/button for a certain padding. By padding, i mean the definition used in [CSS code](https://developer.mozilla.org/en-US/docs/Web/CSS/padding)
- A method to align two elements, supposing the first one is unmovable and the second is our text. Thus the bounds (*x, y, width, height*) of the first element are known

For convenience, these methods should be added in a new class, for example `AlignmentHelper`.

**Comment by Magalii** [comment]
A first version of such methods has been implemented, but it appears that the texts are usually not correctly centered. They are a bit too close to the right border of the screen.
