### ISSUE TITLE
Game 2: Add more STI's

### ISSUE THREAD

**Issue by Magalii** [OpenWeek/app-for-a-KAP#52]
Complete the list of STI's for that game with other existing STI's. The name and symptoms of the STI's need to be added in the string properties files and the setting up of the game needd to be adapted. The names and symptom descriptions have to be in french eventually, but it is ok to write a dummy description like "Syphillis symptoms" for someone who doesn't speak French. One of the French speakers of the development team can add the real description later.
In my opinion, the STI's that need to be added are:
- B Hepatitis (fr: Hépatite B)
- A Hepatitis (fr: Hépatite A)
- Syphilis
- Trichonomas
- Mycosis (fr: Mycose) (Not technically an STI, but still sexually transmissible)
- Morpion (Not an STI, but still sexually transmissible)
- Scabies (fr: Gale) (Not technically an STI, but still sexually transmissible)
For French speakers, this site is a good ressource about STI's and their symptoms: https://depistage.be/

**Comment by FrancoisDuchene** [comment]
Writing the Sti's names, symptoms and descriptions has been moved into the *string.properties* file with commit ba806aa8c4d30e5a2e9aecc8c9b9ab99d9f64293
The translation in English of these descriptions has been done in this commit : 005072feb4f8ff18aa774c16b2b37996378b6b8f

Note that certain fake-sti descriptions haven't be added in French (thus not in English neither). A placeholder is provided.

I'm closing this as done for now, we may reopen this ticket if more info need to be provided.
