### ISSUE TITLE
Game 2 - gameover bug

### ISSUE THREAD

**Issue by FrancoisDuchene** [OpenWeek/app-for-a-KAP#64]
When the player finish the second game by loosing (loosing all it's lives), a game over text still appears but it is still possible to move the balls and winning points by guessing the correct STI's. It shouldn't be possible to be able to still move balls after the end of the game.

Tested on a Xiaomi Redmi Note 6 Pro with Android 9

**Comment by Magalii** [comment]
According to my testing, this has been fixed.
